# Generated by Django 5.0.3 on 2024-05-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_posts_latitude_posts_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='longitude',
        ),
        migrations.AddField(
            model_name='posts',
            name='coordinates',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
