# Generated by Django 5.0.3 on 2024-06-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_posts_coordinates_posts_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
